-- Alkutilanne: rosterit ja minuutit Excelistäsi (Mins-sarake, loukkaantuneet 0).
-- Tämä on pohja, josta joukkueiden nykyiset ORTG/DRTG-luvut koostuvat:
-- kesän muutos = nykyinen rosteri - tämä alkutilanne (EPM x minuutit).
-- "Palauta alkutilanne" -nappi (Transactions) palauttaa pelaajat tähän tilaan.
-- Turvallinen ajaa uudelleen.

create table if not exists season_start_roster (
  id uuid primary key default gen_random_uuid(),
  team text not null,
  name text not null,
  mpg numeric not null default 0,
  in_team boolean not null default true, -- false = kesken kauden treidatun vanha joukkuerivi
  oepm numeric not null default 0,        -- Excelin EPM (varalla, jos pelaajaa ei löydy players-taulusta)
  depm numeric not null default 0,
  unique (team, name)
);
alter table season_start_roster add column if not exists oepm numeric not null default 0;
alter table season_start_roster add column if not exists depm numeric not null default 0;
alter table season_start_roster enable row level security;

delete from season_start_roster;
insert into season_start_roster (team, name, mpg, in_team, oepm, depm) values
  ('Atlanta Hawks', 'Trae Young', 0, false, 3.5, -2.2),
  ('Atlanta Hawks', 'Dyson Daniels', 34, true, 0.3, 2.2),
  ('Atlanta Hawks', 'Zaccharie Risacher', 24, true, -1.4, -1.1),
  ('Atlanta Hawks', 'Jalen Johnson', 36, true, 1.8, 0.6),
  ('Atlanta Hawks', 'Kristaps Porzingis', 0, false, 1.8, 0.9),
  ('Atlanta Hawks', 'Onyeka Okongwu', 24, true, 0.7, 0.1),
  ('Atlanta Hawks', 'CJ McCollum', 30, true, 1.3, -1.4),
  ('Atlanta Hawks', 'Vit Krejci', 0, false, -1.2, -0.6),
  ('Atlanta Hawks', 'Nickeil Alexander-Walker', 30, true, 1.1, 0.3),
  ('Atlanta Hawks', 'Mo Gueye', 20, true, -1.4, 1.5),
  ('Atlanta Hawks', 'Jonathan Kuminga', 24, true, -1.3, 0.3),
  ('Atlanta Hawks', 'Gabe Vincent', 0, true, -2.0, -0.5),
  ('Atlanta Hawks', 'Buddy Hield', 0, true, -0.3, -1.2),
  ('Atlanta Hawks', 'Luke Kennard', 0, false, -0.8, -1.1),
  ('Atlanta Hawks', 'Caleb Houstan', 0, true, -1.9, -0.7),
  ('Atlanta Hawks', 'Asa Newell', 0, true, -1.6, -0.4),
  ('Atlanta Hawks', 'Corey Kispert', 18, true, -0.4, -1.9),
  ('Atlanta Hawks', 'Keaton Wallace', 0, true, -1.5, 0.1),
  ('Atlanta Hawks', 'Chistian Koloko', 0, true, -3.6, 0.2),
  ('Atlanta Hawks', 'Eli John Ndiaye', 0, true, -2.5, -0.6),
  ('Atlanta Hawks', 'Nikola Durisic', 0, true, -2.4, -0.7),
  ('Atlanta Hawks', 'Jock Landale', 0, true, 1.1, -1.7),
  ('Boston Celtics', 'Jayson Tatum', 30, true, 3.6, 1.4),
  ('Boston Celtics', 'Derrick White', 34, true, 2.6, 1.3),
  ('Boston Celtics', 'Jaylen Brown', 34, true, 3.1, -0.1),
  ('Boston Celtics', 'Payton Pritchard', 32, true, 2.0, -0.3),
  ('Boston Celtics', 'Nikola Vucevic', 24, true, 0.8, -1.0),
  ('Boston Celtics', 'Luka Garza', 0, true, 0.8, -1.5),
  ('Boston Celtics', 'Sam Hauser', 24, true, 0.6, -0.2),
  ('Boston Celtics', 'Anfernee Simons', 0, false, 0.6, -1.8),
  ('Boston Celtics', 'Neemias Queta', 26, true, 0.5, 1.5),
  ('Boston Celtics', 'Baylor Scheierman', 14, true, -2.1, 0.0),
  ('Boston Celtics', 'Ron Harper Jr', 0, true, 0.7, -1.3),
  ('Boston Celtics', 'Xavier Tillman', 0, true, -3.2, 0.8),
  ('Boston Celtics', 'Hugo Gonzalez', 22, true, -2.0, 1.2),
  ('Boston Celtics', 'Amari Williams', 0, true, -3.7, 0.1),
  ('Boston Celtics', 'Max Shulga', 0, true, -2.3, -0.8),
  ('Boston Celtics', 'Jordan Walsh', 0, true, -1.5, 0.9),
  ('Brooklyn Nets', 'Cam Thomas', 0, false, 2.5, -2.3),
  ('Brooklyn Nets', 'Day''Ron Sharpe', 0, true, -0.2, 0.9),
  ('Brooklyn Nets', 'Nic Claxton', 0, true, -0.2, 0.0),
  ('Brooklyn Nets', 'Michael Porter Jr', 0, true, 3.6, -1.0),
  ('Brooklyn Nets', 'Josh Minott', 20, true, -1.4, 0.2),
  ('Brooklyn Nets', 'Jalen Wilson', 30, true, -1.7, -1.2),
  ('Brooklyn Nets', 'Ziaire Williams', 0, true, -1.9, -0.1),
  ('Brooklyn Nets', 'Terance Mann', 0, true, -0.4, -1.0),
  ('Brooklyn Nets', 'Noah Clowney', 0, true, -0.6, -0.6),
  ('Brooklyn Nets', 'Egor Demin', 0, true, -0.3, -0.2),
  ('Brooklyn Nets', 'Danny Wolf', 0, true, -1.3, -0.2),
  ('Brooklyn Nets', 'Ben Saraf', 30, true, -3.0, -2.2),
  ('Brooklyn Nets', 'Nolan Traore', 30, true, -2.2, -2.0),
  ('Brooklyn Nets', 'E.J Liddell', 30, true, -1.6, -1.4),
  ('Brooklyn Nets', 'Drake Powell', 30, true, -2.9, -0.1),
  ('Brooklyn Nets', 'Ochai Agbaji', 10, true, -2.3, 0.0),
  ('Brooklyn Nets', 'Chaney Johnson', 20, true, -1.6, 0.2),
  ('Brooklyn Nets', 'Tyson Etienne', 20, true, -0.7, -0.9),
  ('Brooklyn Nets', 'Malachi Smith', 0, true, -2.7, 0.0),
  ('Brooklyn Nets', 'Treveon Scott', 20, true, -2.8, -0.2),
  ('Charlotte Hornets', 'LaMelo Ball', 28, true, 5.0, -0.6),
  ('Charlotte Hornets', 'Miles Bridges', 32, true, 0.9, -0.7),
  ('Charlotte Hornets', 'Brandon Miller', 30, true, 2.0, 0.5),
  ('Charlotte Hornets', 'Coby White', 22, true, 1.5, -1.0),
  ('Charlotte Hornets', 'Collin Sexton', 0, false, 1.3, -1.6),
  ('Charlotte Hornets', 'Moussa Diabate', 24, true, 0.4, 0.7),
  ('Charlotte Hornets', 'Grant Williams', 18, true, -1.2, 0.0),
  ('Charlotte Hornets', 'Tre Mann', 0, true, -1.2, -1.8),
  ('Charlotte Hornets', 'Josh Green', 8, true, -1.7, -0.8),
  ('Charlotte Hornets', 'Kon Knueppel', 32, true, 0.6, -0.7),
  ('Charlotte Hornets', 'Pat Connaughton', 0, true, -1.2, -1.0),
  ('Charlotte Hornets', 'Mason Plumlee', 0, true, -1.5, -1.5),
  ('Charlotte Hornets', 'Drew Peterson', 0, true, -2.1, -0.9),
  ('Charlotte Hornets', 'Ryan Kalkbrenner', 22, true, -2.2, -0.2),
  ('Charlotte Hornets', 'Liam McNeeley', 0, true, -2.4, -1.1),
  ('Charlotte Hornets', 'Sion James', 24, true, -2.7, 0.4),
  ('Charlotte Hornets', 'Antonio Reeves', 0, true, -1.4, -1.4),
  ('Charlotte Hornets', 'KJ Simpson', 0, true, -2.7, -1.0),
  ('Charlotte Hornets', 'Tidjaune Salaun', 0, true, -2.9, 0.0),
  ('Charlotte Hornets', 'Ibou Badji', 0, true, -4.5, -1.4),
  ('Chicago Bulls', 'Josh Giddey', 0, true, 1.3, -0.2),
  ('Chicago Bulls', 'Nikola Vucevic', 0, false, 1.0, -1.2),
  ('Chicago Bulls', 'Jalen Smith', 0, true, 1.6, -0.4),
  ('Chicago Bulls', 'Coby White', 0, false, 2.0, -0.7),
  ('Chicago Bulls', 'Tre Jones', 30, true, 0.8, -0.3),
  ('Chicago Bulls', 'Anfernee Simons', 0, true, 1.5, -1.6),
  ('Chicago Bulls', 'Collin Sexton', 30, true, 0.7, -1.6),
  ('Chicago Bulls', 'Leonard Miller', 30, true, -1.6, -1.5),
  ('Chicago Bulls', 'Nick Richards', 0, false, -1.7, -2.2),
  ('Chicago Bulls', 'Isaac Okoro', 30, true, 0.2, -0.6),
  ('Chicago Bulls', 'Kevin Huerter', 0, false, 0.4, -0.5),
  ('Chicago Bulls', 'Zach Collins', 0, true, -1.1, -0.6),
  ('Chicago Bulls', 'Rob Dillingham', 30, true, -4.3, -0.6),
  ('Chicago Bulls', 'Matas Buzelis', 0, true, -0.1, -0.1),
  ('Chicago Bulls', 'Ayo Dosunmu', 0, false, 0.4, -0.8),
  ('Chicago Bulls', 'Noa Essengue', 0, true, -2.4, -0.2),
  ('Chicago Bulls', 'Guerschon Yabusele', 30, true, 0.0, -0.9),
  ('Chicago Bulls', 'Patrick Williams', 30, true, -3.4, -0.4),
  ('Chicago Bulls', 'Lahlan Olbrich', 20, true, -2.7, -0.2),
  ('Chicago Bulls', 'Yuki Kawamura', 10, true, -0.5, -2.1),
  ('Cleveland Cavaliers', 'Donovan Mitchell', 18, true, 5.5, 0.1),
  ('Cleveland Cavaliers', 'Jarrett Allen', 28, true, 1.8, 1.6),
  ('Cleveland Cavaliers', 'Evan Mobley', 32, true, 1.2, 1.3),
  ('Cleveland Cavaliers', 'James Harden', 36, true, 3.7, -0.6),
  ('Cleveland Cavaliers', 'Darius Garland', 0, false, 2.3, -1.4),
  ('Cleveland Cavaliers', 'Lonzo Ball', 0, true, -1.1, 1.6),
  ('Cleveland Cavaliers', 'Max Strus', 20, true, 1.1, 0.3),
  ('Cleveland Cavaliers', 'Sam Merrill', 26, true, 1.0, 0.7),
  ('Cleveland Cavaliers', 'Dean Wade', 11, true, -1.3, 1.4),
  ('Cleveland Cavaliers', 'Dennis Schröder', 20, true, -0.4, -0.2),
  ('Cleveland Cavaliers', 'Keon Ellis', 20, true, -2.0, 0.7),
  ('Cleveland Cavaliers', 'De''Andre Hunter', 0, false, 0.6, -1.3),
  ('Cleveland Cavaliers', 'Nae''Qwan Tomlin', 17, true, -0.4, 0.3),
  ('Cleveland Cavaliers', 'Larry Nance Jr', 0, true, -2.1, 0.0),
  ('Cleveland Cavaliers', 'Jaylon Tyson', 12, true, 0.2, -0.2),
  ('Cleveland Cavaliers', 'Thomas Bryant', 0, true, -1.5, -0.5),
  ('Cleveland Cavaliers', 'Craig Porter Jr', 0, true, -2.0, -0.3),
  ('Cleveland Cavaliers', 'Tyrese Proctor', 0, true, 0.2, -0.4),
  ('Cleveland Cavaliers', 'Luke Travers', 0, true, -1.8, -1.1),
  ('Dallas Mavericks', 'Kyrie Irving', 0, true, 3.5, 0.4),
  ('Dallas Mavericks', 'Anthony Davis', 0, true, 2.3, 1.2),
  ('Dallas Mavericks', 'Dereck Lively', 0, true, -0.4, 1.1),
  ('Dallas Mavericks', 'D''Angelo Russell', 0, true, 1.2, 0.0),
  ('Dallas Mavericks', 'Daniel Gafford', 15, true, -0.8, 0.3),
  ('Dallas Mavericks', 'P.J Washington', 15, true, -2.0, 0.9),
  ('Dallas Mavericks', 'Brandon Williams', 15, true, -0.2, -0.2),
  ('Dallas Mavericks', 'Khris Middleton', 30, true, -0.2, -0.3),
  ('Dallas Mavericks', 'Klay Thompson', 20, true, -0.7, 0.1),
  ('Dallas Mavericks', 'Naji Marshall', 10, true, 0.1, 0.5),
  ('Dallas Mavericks', 'Marvin Bagley', 25, true, -0.5, -0.8),
  ('Dallas Mavericks', 'Tyus Jones', 0, true, -1.3, -1.4),
  ('Dallas Mavericks', 'Cooper Flagg', 30, true, 0.5, -0.3),
  ('Dallas Mavericks', 'Dwight Powell', 0, true, -1.3, 0.3),
  ('Dallas Mavericks', 'Max Christie', 30, true, -0.1, -0.3),
  ('Dallas Mavericks', 'Caleb Martin', 0, true, -3.1, 1.0),
  ('Dallas Mavericks', 'Moussa Cisse', 0, true, -3.1, -1.2),
  ('Dallas Mavericks', 'Ryan Nembhard', 30, true, -1.1, -1.1),
  ('Dallas Mavericks', 'Miles Kelly', 0, true, -2.0, -0.8),
  ('Dallas Mavericks', 'AJ Johnson', 20, true, -3.9, -1.0),
  ('Denver Nuggets', 'Nikola Jokic', 36, true, 7.6, 1.0),
  ('Denver Nuggets', 'Christian Braun', 30, true, -0.9, 1.0),
  ('Denver Nuggets', 'Jamal Murray', 36, true, 4.5, -1.2),
  ('Denver Nuggets', 'Cameron Johnson', 30, true, 1.3, -0.4),
  ('Denver Nuggets', 'Aaron Gordon', 30, true, 1.6, 0.9),
  ('Denver Nuggets', 'Tim Hardaway Jr', 25, true, 1.0, -1.4),
  ('Denver Nuggets', 'Jonas Valanciunas', 8, true, 0.7, -1.9),
  ('Denver Nuggets', 'Daron Holmes', 0, true, -0.6, -0.1),
  ('Denver Nuggets', 'Spencer Jones', 0, true, -2.0, 0.5),
  ('Denver Nuggets', 'Jalen Pickett', 0, true, -0.9, -0.3),
  ('Denver Nuggets', 'Hunter Tyson', 0, true, -1.6, -1.2),
  ('Denver Nuggets', 'Zeke Nnaji', 0, true, -2.5, -0.1),
  ('Denver Nuggets', 'Tamar Bates', 0, true, -2.1, -0.9),
  ('Denver Nuggets', 'Payton Watson', 0, true, -0.2, 0.1),
  ('Denver Nuggets', 'Curtis Jones', 0, true, -1.0, -1.1),
  ('Denver Nuggets', 'Bruce Brown', 30, true, -3.0, -1.2),
  ('Denver Nuggets', 'Julian Strawther', 15, true, -2.5, -1.1),
  ('Detroit Pistons', 'Cade Cunningham', 18, true, 3.7, 1.0),
  ('Detroit Pistons', 'Ausar Thompson', 30, true, -0.8, 3.2),
  ('Detroit Pistons', 'Tobias Harris', 36, true, 0.0, 0.6),
  ('Detroit Pistons', 'Paul Reed', 11, true, -0.6, 2.6),
  ('Detroit Pistons', 'Jalen Duren', 26, true, 2.5, 0.8),
  ('Detroit Pistons', 'Caris LeVert', 10, true, -1.4, 0.5),
  ('Detroit Pistons', 'Javonte Green', 0, true, -1.4, 1.8),
  ('Detroit Pistons', 'Marcus Sasser', 18, true, 0.1, 0.0),
  ('Detroit Pistons', 'Duncan Robinson', 18, true, 1.3, -0.2),
  ('Detroit Pistons', 'Ron Holland', 18, true, -2.5, 3.0),
  ('Detroit Pistons', 'Isaiah Stewart', 11, true, -1.3, -0.1),
  ('Detroit Pistons', 'Kevin Huerter', 20, true, -0.1, -0.1),
  ('Detroit Pistons', 'Daniss Jenkins', 24, true, 0.0, 1.2),
  ('Detroit Pistons', 'Jaden Ivey', 0, true, -0.7, -1.6),
  ('Detroit Pistons', 'Bobi Klintman', 0, true, -2.1, -0.3),
  ('Detroit Pistons', 'Colby Jones', 0, true, -2.5, -0.1),
  ('Detroit Pistons', 'Isaac Jones', 0, true, -2.5, -0.8),
  ('Detroit Pistons', 'Wendell Moore Jr', 0, true, -3.7, 0.2),
  ('Golden State Warriors', 'Steph Curry', 32, true, 6.4, -1.1),
  ('Golden State Warriors', 'Jimmy Butler', 0, true, 3.2, 1.2),
  ('Golden State Warriors', 'De''Anthony Melton', 22, true, 1.2, 1.6),
  ('Golden State Warriors', 'Kristaps Porzingis', 15, true, 1.9, 0.9),
  ('Golden State Warriors', 'Brandin Podziemski', 26, true, -0.4, 1.6),
  ('Golden State Warriors', 'Draymond Green', 26, true, -2.0, 1.5),
  ('Golden State Warriors', 'Al Horford', 0, true, -0.2, 0.3),
  ('Golden State Warriors', 'Gary Payton', 30, true, -0.8, 1.0),
  ('Golden State Warriors', 'Moses Moody', 0, true, 0.0, 1.5),
  ('Golden State Warriors', 'Gui Santos', 0, true, -0.3, 0.9),
  ('Golden State Warriors', 'Jonathan Kuminga', 0, false, -0.6, 0.3),
  ('Golden State Warriors', 'Quinten Post', 0, true, 0.1, 0.2),
  ('Golden State Warriors', 'Jackson Rowe', 9, true, -1.8, -0.1),
  ('Golden State Warriors', 'Pat Spencer', 20, true, -0.9, 0.1),
  ('Golden State Warriors', 'Alex Toohey', 30, true, -2.7, -0.4),
  ('Golden State Warriors', 'Will Richard', 30, true, -1.7, 0.9),
  ('Houston Rockets', 'Amen Thompson', 36, true, 1.0, 2.6),
  ('Houston Rockets', 'Alperen Sengun', 36, true, 1.6, 1.4),
  ('Houston Rockets', 'Kevin Durant', 36, true, 2.1, 0.1),
  ('Houston Rockets', 'Dorian Finney-Smith', 18, true, -0.3, 1.3),
  ('Houston Rockets', 'Tari Easton', 24, true, -0.6, 1.1),
  ('Houston Rockets', 'Josh Okogie', 0, true, -1.0, 1.5),
  ('Houston Rockets', 'Steven Adams', 0, true, -0.7, 0.8),
  ('Houston Rockets', 'Clint Capela', 20, true, -0.8, 0.4),
  ('Houston Rockets', 'Jabari Smith Jr', 30, true, -1.1, 0.3),
  ('Houston Rockets', 'Aaron Holiday', 18, true, -0.9, 0.0),
  ('Houston Rockets', 'Jae''Sean Tate', 0, true, -2.4, 0.8),
  ('Houston Rockets', 'JD Davidson', 0, true, -1.9, -0.6),
  ('Houston Rockets', 'Kevon Harris', 0, true, -3.2, 0.7),
  ('Houston Rockets', 'Jeff Green', 0, true, -1.3, -1.7),
  ('Houston Rockets', 'Reed Sheppard', 22, true, -2.4, -0.7),
  ('Houston Rockets', 'Isaiah Crawford', 0, true, -3.3, -0.5),
  ('Indiana Pacers', 'Tyrese Haliburton', 0, true, 4.6, -0.7),
  ('Indiana Pacers', 'Pascal Siakam', 0, true, 2.1, 1.4),
  ('Indiana Pacers', 'Aaron Nesmith', 0, true, 0.6, 0.8),
  ('Indiana Pacers', 'Andrew Nembhard', 0, true, 1.3, 1.8),
  ('Indiana Pacers', 'Quenton Jackson', 30, true, -1.1, 0.2),
  ('Indiana Pacers', 'TJ McConnell', 0, true, 0.0, -0.4),
  ('Indiana Pacers', 'Ivica Zubac', 0, true, -0.4, 0.8),
  ('Indiana Pacers', 'Obi Toppin', 30, true, 0.5, -1.7),
  ('Indiana Pacers', 'Jay Huff', 30, true, -1.3, -1.0),
  ('Indiana Pacers', 'Micah Potter', 30, true, -1.6, -1.1),
  ('Indiana Pacers', 'Ethan Thompson', 30, true, -1.6, -0.3),
  ('Indiana Pacers', 'Bennedict Mathurin', 0, false, -0.4, -1.0),
  ('Indiana Pacers', 'Ben Sheppard', 14, true, -2.0, -0.8),
  ('Indiana Pacers', 'Johnny Furphy', 0, true, -1.9, 0.1),
  ('Indiana Pacers', 'Kam Jones', 30, true, -2.6, -0.7),
  ('Indiana Pacers', 'Kobe Brown', 30, true, -2.0, -0.8),
  ('Indiana Pacers', 'Taelon Peter', 0, true, -1.8, -0.8),
  ('Indiana Pacers', 'Jarace Walker', 16, true, -3.0, -0.6),
  ('Los Angeles Clippers', 'Kawhi Leonard', 32, true, 6.3, 1.4),
  ('Los Angeles Clippers', 'Ivica Zubac', 0, false, -0.5, 0.7),
  ('Los Angeles Clippers', 'Darius Garland', 30, true, 1.6, -1.1),
  ('Los Angeles Clippers', 'James Harden', 0, false, 3.2, -0.7),
  ('Los Angeles Clippers', 'Kris Dunn', 20, true, -0.9, 1.9),
  ('Los Angeles Clippers', 'John Collins', 26, true, 0.0, -0.4),
  ('Los Angeles Clippers', 'Brook Lopez', 26, true, -0.4, 1.1),
  ('Los Angeles Clippers', 'Derrick Jones Jr', 30, true, -0.2, 1.1),
  ('Los Angeles Clippers', 'Bennedict Mathurin', 30, true, -0.5, -0.1),
  ('Los Angeles Clippers', 'Bogdan Bogdanovic', 10, true, -0.6, 0.1),
  ('Los Angeles Clippers', 'Nicolas Batum', 20, true, -2.4, 0.3),
  ('Los Angeles Clippers', 'Bradley Beal', 0, true, -0.5, -0.8),
  ('Los Angeles Clippers', 'Cam Christie', 0, true, -2.6, 0.1),
  ('Los Angeles Clippers', 'Jordan Miller', 0, true, -1.1, -0.8),
  ('Los Angeles Clippers', 'Isaiah Jackson', 16, true, -2.0, -0.6),
  ('Los Angeles Clippers', 'Norchad Omier', 0, true, -2.6, -0.6),
  ('Los Angeles Clippers', 'Yanic Konan Niederhauser', 0, true, -2.2, -0.9),
  ('Los Angeles Clippers', 'Kobe Sanders', 0, true, -2.1, -0.4),
  ('Los Angeles Clippers', 'Jahmyl Telfort', 0, true, -2.9, -0.7),
  ('Los Angeles Lakers', 'Luka Doncic', 0, true, 6.2, 0.4),
  ('Los Angeles Lakers', 'Austin Reaves', 0, true, 4.0, -0.1),
  ('Los Angeles Lakers', 'LeBron James', 15, true, 1.9, -0.3),
  ('Los Angeles Lakers', 'Marcus Smart', 0, true, -1.0, 1.4),
  ('Los Angeles Lakers', 'Rui Hachimura', 28, true, -0.7, -0.3),
  ('Los Angeles Lakers', 'Jaxson Hayes', 18, true, -1.4, -0.4),
  ('Los Angeles Lakers', 'DeAndre Ayton', 30, true, -1.3, -0.3),
  ('Los Angeles Lakers', 'Jarred Vanderbilt', 18, true, -2.4, 0.5),
  ('Los Angeles Lakers', 'Jake LaRavia', 30, true, -0.9, -0.9),
  ('Los Angeles Lakers', 'Luke Kennard', 30, true, -0.7, -1.2),
  ('Los Angeles Lakers', 'Gabe Vincent', 0, false, -2.0, -0.4),
  ('Los Angeles Lakers', 'Dalton Knecht', 30, true, -1.3, -1.7),
  ('Los Angeles Lakers', 'Adou Thiero', 0, true, -3.5, -0.8),
  ('Los Angeles Lakers', 'Christian Koloko', 0, true, -2.8, -0.4),
  ('Los Angeles Lakers', 'Chris Manon', 0, true, -2.8, -0.9),
  ('Los Angeles Lakers', 'Bronny James', 15, true, -2.7, -1.2),
  ('Los Angeles Lakers', 'Maxi Kleber', 0, true, -2.8, -0.7),
  ('Los Angeles Lakers', 'Nick Smith Jr', 26, true, -2.1, -2.4),
  ('Memphis Grizzlies', 'Ja Morant', 0, true, 2.0, 0.2),
  ('Memphis Grizzlies', 'Ty Jerome', 0, true, 5.4, -0.2),
  ('Memphis Grizzlies', 'Jaren Jackson Jr', 0, false, -0.6, 1.1),
  ('Memphis Grizzlies', 'Jaylen Wells', 0, true, 1.2, -0.8),
  ('Memphis Grizzlies', 'Scottie Pippen Jr', 0, true, -0.3, 1.4),
  ('Memphis Grizzlies', 'Brandon Clarke', 0, true, -0.6, 0.6),
  ('Memphis Grizzlies', 'Zach Edey', 0, true, 0.4, 1.4),
  ('Memphis Grizzlies', 'Kentavious Caldwell-Pope', 0, true, -1.3, 0.7),
  ('Memphis Grizzlies', 'Santi Aldama', 0, true, 0.2, -0.2),
  ('Memphis Grizzlies', 'Cam Spencer', 0, true, 1.7, -1.2),
  ('Memphis Grizzlies', 'DeJon Jarreau', 0, true, -2.3, -0.6),
  ('Memphis Grizzlies', 'Olivier Maxence-Prosper', 0, true, -1.1, -0.7),
  ('Memphis Grizzlies', 'GG Jackson', 0, true, -0.1, -1.4),
  ('Memphis Grizzlies', 'Cedric Coward', 25, true, 0.3, 0.1),
  ('Memphis Grizzlies', 'Javon Small', 0, true, 0.7, -0.7),
  ('Memphis Grizzlies', 'Walter Clayton Jr', 30, true, -0.7, -1.4),
  ('Memphis Grizzlies', 'Jahmai Mashack', 15, true, -3.3, -1.0),
  ('Memphis Grizzlies', 'Lawson Lovering', 0, true, -2.6, 0.2),
  ('Memphis Grizzlies', 'Taylor Hendricks', 20, true, -1.3, -1.1),
  ('Memphis Grizzlies', 'Dariq Whitehead', 40, true, -2.3, -0.6),
  ('Memphis Grizzlies', 'Adama Bal', 30, true, -3.1, -0.3),
  ('Memphis Grizzlies', 'Tyler Burton', 30, true, -2.8, -0.4),
  ('Memphis Grizzlies', 'Taj Gibson', 10, true, -4.0, -0.3),
  ('Memphis Grizzlies', 'Rayan Rupert', 40, true, -4.2, -0.8),
  ('Miami Heat', 'Bam Adebayo', 36, true, 0.3, 1.8),
  ('Miami Heat', 'Tyler Herro', 36, true, 2.1, -0.6),
  ('Miami Heat', 'Norman Powell', 30, true, 0.4, 0.0),
  ('Miami Heat', 'Kel''El Ware', 20, true, -0.5, 0.2),
  ('Miami Heat', 'Davion Mitchell', 20, true, -1.2, 0.8),
  ('Miami Heat', 'Andrew Wiggins', 28, true, -0.8, -0.4),
  ('Miami Heat', 'Nikola Jovic', 0, true, -1.1, -0.1),
  ('Miami Heat', 'Jaime Jaquez', 20, true, -1.2, -0.7),
  ('Miami Heat', 'Simone Fontecchio', 20, true, -1.6, -0.5),
  ('Miami Heat', 'Pelle Larsson', 22, true, -1.9, -0.3),
  ('Miami Heat', 'Dru Smith', 8, true, -3.0, 0.7),
  ('Miami Heat', 'Terry Rozier', 0, true, -1.7, -1.3),
  ('Miami Heat', 'Vladislav Goldin', 0, true, -3.0, -0.1),
  ('Miami Heat', 'Kasparas Jakucionis', 0, true, -2.6, -0.6),
  ('Miami Heat', 'Myron Gardner', 0, true, -2.7, -0.6),
  ('Miami Heat', 'Jahimir Young', 0, true, -2.8, -0.7),
  ('Miami Heat', 'Keshad Johnson', 0, true, -3.3, -0.9),
  ('Milwaukee Bucks', 'Giannis Antetokounmpo', 0, true, 5.1, 1.1),
  ('Milwaukee Bucks', 'Myles Turner', 15, true, 0.8, 0.4),
  ('Milwaukee Bucks', 'Bobby Portis', 10, true, 0.2, -0.9),
  ('Milwaukee Bucks', 'Gary Trent Jr', 10, true, -0.7, -2.0),
  ('Milwaukee Bucks', 'AJ Green', 30, true, 0.4, 0.3),
  ('Milwaukee Bucks', 'Ryan Rollins', 15, true, 0.6, 0.2),
  ('Milwaukee Bucks', 'Cam Thomas', 0, true, 1.2, -2.5),
  ('Milwaukee Bucks', 'Kevin Porter Jr', 0, true, -0.2, 0.2),
  ('Milwaukee Bucks', 'Gary Harris', 12, true, -3.2, 0.2),
  ('Milwaukee Bucks', 'Taurean Prince', 0, true, -2.1, -0.4),
  ('Milwaukee Bucks', 'Ousmane Dieng', 30, true, -2.5, -0.1),
  ('Milwaukee Bucks', 'Cormac Ryan', 30, true, -1.7, -0.3),
  ('Milwaukee Bucks', 'Andre Jackson Jr', 15, true, -2.4, -0.4),
  ('Milwaukee Bucks', 'Jericho Sims', 28, true, -4.2, -1.3),
  ('Milwaukee Bucks', 'Kyle Kuzma', 15, true, -2.5, -1.3),
  ('Milwaukee Bucks', 'Pete Nance', 30, true, -2.9, -1.5),
  ('Milwaukee Bucks', 'Thanasis Antetokounmpo', 0, true, -4.0, 0.1),
  ('Minnesota Timberwolves', 'Anthony Edwards', 0, true, 3.2, -0.1),
  ('Minnesota Timberwolves', 'Rudy Gobert', 30, true, -0.7, 3.0),
  ('Minnesota Timberwolves', 'Jaden McDaniels', 0, true, 0.1, 1.4),
  ('Minnesota Timberwolves', 'Mike Conley', 28, true, -0.9, -0.1),
  ('Minnesota Timberwolves', 'Julius Randle', 36, true, 2.3, -0.7),
  ('Minnesota Timberwolves', 'Naz Reid', 30, true, 0.2, 0.8),
  ('Minnesota Timberwolves', 'Donte DiVincenzo', 21, true, 1.4, 0.5),
  ('Minnesota Timberwolves', 'Ayo Dosunmu', 20, true, -0.1, -0.7),
  ('Minnesota Timberwolves', 'Bones Hyland', 20, true, 0.5, -0.2),
  ('Minnesota Timberwolves', 'Jaylen Clark', 19, true, -2.2, 1.4),
  ('Minnesota Timberwolves', 'Julian Phillips', 0, true, -2.3, 0.3),
  ('Minnesota Timberwolves', 'Terrence Shannon Jr', 36, true, -2.7, -0.3),
  ('Minnesota Timberwolves', 'Joe Ingles', 0, true, -2.7, -0.3),
  ('Minnesota Timberwolves', 'Joan Beringer', 0, true, -2.0, -1.1),
  ('Minnesota Timberwolves', 'Johnny Juzang', 0, true, -0.6, -1.8),
  ('Minnesota Timberwolves', 'Rocco Zikarsky', 0, true, -2.8, -0.2),
  ('Minnesota Timberwolves', 'Enrique Freeman', 0, true, -3.3, -0.8),
  ('New Orleans Pelicans', 'Zion Williamson', 30, true, 1.1, -0.6),
  ('New Orleans Pelicans', 'Trey Murphy III', 0, true, 3.1, -0.6),
  ('New Orleans Pelicans', 'Herb Jones', 30, true, -1.1, 1.6),
  ('New Orleans Pelicans', 'Jose Alvarado', 0, false, -0.9, 1.1),
  ('New Orleans Pelicans', 'Saddiq Bey', 30, true, 2.0, -0.9),
  ('New Orleans Pelicans', 'Dejounte Murray', 12, true, 0.5, -0.3),
  ('New Orleans Pelicans', 'Jordan Poole', 12, true, 0.2, -1.4),
  ('New Orleans Pelicans', 'Kevon Looney', 0, true, -1.6, 0.3),
  ('New Orleans Pelicans', 'Jaden Springer', 0, true, -2.6, 0.1),
  ('New Orleans Pelicans', 'DeAndre Jordan', 9, true, -2.8, -0.7),
  ('New Orleans Pelicans', 'Karlo Matkovic', 18, true, -2.3, -0.8),
  ('New Orleans Pelicans', 'Derik Queen', 26, true, -1.5, -0.6),
  ('New Orleans Pelicans', 'Jeremiah Fears', 26, true, -1.6, -0.8),
  ('New Orleans Pelicans', 'Hunter Dickinson', 0, true, -3.0, -1.2),
  ('New Orleans Pelicans', 'Micah Peavy', 18, true, -2.1, -0.1),
  ('New Orleans Pelicans', 'Bryce McGowens', 0, true, -1.5, -1.0),
  ('New Orleans Pelicans', 'Yves Missi', 16, true, -1.6, -1.2),
  ('New Orleans Pelicans', 'Jordan Hawkins', 13, true, -2.8, -2.0),
  ('New Orleans Pelicans', 'Trey Alexander', 0, true, -2.9, -1.1),
  ('New York Knicks', 'Karl-Anthony Towns', 36, true, 2.6, 0.8),
  ('New York Knicks', 'Jalen Brunson', 36, true, 5.5, -1.8),
  ('New York Knicks', 'OG Anunoby', 30, true, 0.4, 1.7),
  ('New York Knicks', 'Mitchell Robinson', 28, true, 0.1, 1.3),
  ('New York Knicks', 'Miles McBride', 24, true, 0.9, 1.0),
  ('New York Knicks', 'Josh Hart', 24, true, 0.4, 0.2),
  ('New York Knicks', 'Mikal Bridges', 30, true, 0.9, 0.5),
  ('New York Knicks', 'Jose Alvarado', 24, true, -1.8, 0.7),
  ('New York Knicks', 'Jordan Clarkson', 0, true, -0.8, -1.6),
  ('New York Knicks', 'Landry Shamet', 0, true, -1.3, -0.3),
  ('New York Knicks', 'Tyler Kolek', 0, true, -1.0, 0.2),
  ('New York Knicks', 'Tosan Evbuomwan', 0, true, -2.4, -0.5),
  ('New York Knicks', 'Mohamed Diawara', 0, true, -2.6, -0.5),
  ('New York Knicks', 'Kevin McCullar Jr', 0, true, -2.8, -0.7),
  ('New York Knicks', 'Pacome Dadiet', 0, true, -2.6, -1.0),
  ('New York Knicks', 'Ariel Hukpoti', 8, true, -4.3, -0.1),
  ('Oklahoma City Thunder', 'Shai Gilgeous-Alexander', 35, true, 6.6, 1.8),
  ('Oklahoma City Thunder', 'Chet Holmgren', 30, true, 1.4, 3.0),
  ('Oklahoma City Thunder', 'Jalen Williams', 0, true, 1.0, 1.2),
  ('Oklahoma City Thunder', 'Isaiah Hartenstein', 25, true, 0.2, 1.9),
  ('Oklahoma City Thunder', 'Isaiah Joe', 22, true, 1.1, -0.2),
  ('Oklahoma City Thunder', 'Aaron Wiggins', 18, true, 0.5, 0.6),
  ('Oklahoma City Thunder', 'Alex Caruso', 15, true, -0.8, 3.3),
  ('Oklahoma City Thunder', 'Jaylin Williams', 15, true, -0.2, 2.4),
  ('Oklahoma City Thunder', 'Kenrich Williams', 0, true, -0.3, 1.1),
  ('Oklahoma City Thunder', 'Cason Wallace', 30, true, -1.5, 3.1),
  ('Oklahoma City Thunder', 'Lu Dort', 30, true, -0.7, 0.8),
  ('Oklahoma City Thunder', 'Jared McCain', 0, true, -0.8, -0.5),
  ('Oklahoma City Thunder', 'Branden Carlson', 0, true, -0.6, -0.8),
  ('Oklahoma City Thunder', 'Nikola Topic', 0, true, -1.9, 0.1),
  ('Oklahoma City Thunder', 'Ajay Mitchell', 20, true, 0.0, 2.4),
  ('Oklahoma City Thunder', 'Ousmane Dieng', 0, false, -2.5, 0.3),
  ('Oklahoma City Thunder', 'Jazian Gortman', 0, true, -2.5, -0.1),
  ('Oklahoma City Thunder', 'Thomas Sorber', 0, true, -2.9, -0.2),
  ('Oklahoma City Thunder', 'Brooks Barnhizer', 0, true, -4.3, 0.0),
  ('Oklahoma City Thunder', 'Chris Youngblood', 0, true, -2.7, -0.7),
  ('Oklahoma City Thunder', 'Malevy Leons', 0, true, -3.5, -0.3),
  ('Orlando Magic', 'Franz Wagner', 20, true, 1.9, 1.4),
  ('Orlando Magic', 'Jalen Suggs', 30, true, 0.7, 2.5),
  ('Orlando Magic', 'Desmond Bane', 34, true, 2.3, -0.2),
  ('Orlando Magic', 'Moritz Wagner', 12, true, 0.9, 0.2),
  ('Orlando Magic', 'Jonathan Isaac', 0, true, -2.7, 2.2),
  ('Orlando Magic', 'Paolo Banchero', 36, true, 1.0, 0.6),
  ('Orlando Magic', 'Wendell Carter Jr', 28, true, -0.6, 1.6),
  ('Orlando Magic', 'Goga Bitadze', 14, true, -0.2, 1.2),
  ('Orlando Magic', 'Tyus Jones', 0, false, 0.7, -1.4),
  ('Orlando Magic', 'Anthony Black', 0, true, -0.5, 0.6),
  ('Orlando Magic', 'Jevon Carter', 20, true, -0.5, -0.6),
  ('Orlando Magic', 'Orlando Robinson', 0, true, -1.6, -0.8),
  ('Orlando Magic', 'Colin Castleton', 0, true, -2.4, -0.8),
  ('Orlando Magic', 'Jamal Cain', 0, true, -1.6, -0.7),
  ('Orlando Magic', 'Tristan Da Silva', 30, true, -1.7, 0.3),
  ('Orlando Magic', 'Alex Morales', 0, true, -2.8, -0.5),
  ('Orlando Magic', 'Noah Penda', 0, true, -1.7, -0.5),
  ('Orlando Magic', 'Jase Richardson', 0, true, -2.0, -0.7),
  ('Orlando Magic', 'Jett Howard', 0, true, -0.8, -1.2),
  ('Philadelphia 76ers', 'Joel Embiid', 30, true, 3.2, 0.9),
  ('Philadelphia 76ers', 'Tyrese Maxey', 40, true, 4.9, -0.7),
  ('Philadelphia 76ers', 'Paul George', 30, true, -0.3, 0.8),
  ('Philadelphia 76ers', 'Andre Drummond', 20, true, -1.6, 0.8),
  ('Philadelphia 76ers', 'Jared McCain', 0, false, -0.3, -0.6),
  ('Philadelphia 76ers', 'Quentin Grimes', 35, true, 0.7, -1.8),
  ('Philadelphia 76ers', 'Kelly Oubre Jr', 20, true, -0.9, -0.5),
  ('Philadelphia 76ers', 'Kyle Lowry', 0, true, -1.9, 0.4),
  ('Philadelphia 76ers', 'Trendon Watford', 30, true, -1.7, -0.2),
  ('Philadelphia 76ers', 'Dominick Barlow', 0, true, -1.2, -0.7),
  ('Philadelphia 76ers', 'Jabari Walker', 0, true, -1.8, -0.2),
  ('Philadelphia 76ers', 'Eric Gordon', 0, true, -1.2, -1.0),
  ('Philadelphia 76ers', 'VJ Edgecombe', 35, true, -2.0, -0.7),
  ('Philadelphia 76ers', 'Adem Bona', 0, true, -2.4, -0.6),
  ('Philadelphia 76ers', 'Johni Broome', 0, true, -2.8, -0.3),
  ('Philadelphia 76ers', 'Hunter Sallis', 0, true, -2.5, -0.7),
  ('Philadelphia 76ers', 'Justin Edwards', 0, true, -1.4, -1.9),
  ('Phoenix Suns', 'Devin Booker', 36, true, 3.8, -0.8),
  ('Phoenix Suns', 'Collin Gillespie', 28, true, 1.9, 0.8),
  ('Phoenix Suns', 'Grayson Allen', 30, true, 2.6, -0.7),
  ('Phoenix Suns', 'Jalen Green', 26, true, 0.7, -0.5),
  ('Phoenix Suns', 'Dillon Brooks', 30, true, 0.0, 0.7),
  ('Phoenix Suns', 'Royce O''Neale', 30, true, -0.5, -0.3),
  ('Phoenix Suns', 'Mark Williams', 25, true, -0.3, 0.2),
  ('Phoenix Suns', 'Ryan Dunn', 16, true, -0.9, -0.3),
  ('Phoenix Suns', 'Jordan Goodwin', 0, true, -2.3, 0.1),
  ('Phoenix Suns', 'Khaman Maluach', 0, true, -2.4, -0.1),
  ('Phoenix Suns', 'Damion Baugh', 0, true, -2.5, -0.2),
  ('Phoenix Suns', 'Rasheer Fleming', 0, true, -2.5, -0.3),
  ('Phoenix Suns', 'CJ Huntley', 0, true, -2.5, -0.3),
  ('Phoenix Suns', 'Jamaree Bouyea', 0, true, -1.3, -0.2),
  ('Phoenix Suns', 'Nick Richards', 0, true, -1.0, -2.0),
  ('Phoenix Suns', 'Oso Ighodaro', 19, true, -3.6, 0.4),
  ('Phoenix Suns', 'Isaiah Livers', 0, true, -2.4, -0.9),
  ('Phoenix Suns', 'Amir Coffey', 0, true, -2.5, -0.7),
  ('Portland Trail Blazers', 'Deni Avdija', 34, true, 4.0, -0.8),
  ('Portland Trail Blazers', 'Toumani Camara', 34, true, -0.5, 1.3),
  ('Portland Trail Blazers', 'Jrue Holiday', 28, true, 1.3, 1.0),
  ('Portland Trail Blazers', 'Donovan Clingan', 28, true, 1.9, 0.4),
  ('Portland Trail Blazers', 'Shaedon Sharpe', 0, true, -0.4, -0.6),
  ('Portland Trail Blazers', 'Matisse Thybulle', 16, true, -2.4, 2.0),
  ('Portland Trail Blazers', 'Robert Williams III', 16, true, -0.8, 0.2),
  ('Portland Trail Blazers', 'Jerami Grant', 0, true, 1.0, -0.9),
  ('Portland Trail Blazers', 'Vit Krejci', 0, true, -1.0, -0.4),
  ('Portland Trail Blazers', 'Kris Murray', 20, true, -3.2, 1.1),
  ('Portland Trail Blazers', 'Scoot Henderson', 26, true, -0.9, -0.9),
  ('Portland Trail Blazers', 'Yang Hansen', 0, true, -3.4, -1.4),
  ('Portland Trail Blazers', 'Caleb Love', 16, true, -0.8, -1.2),
  ('Portland Trail Blazers', 'Sidy Cissoko', 22, true, -2.2, 0.4),
  ('Portland Trail Blazers', 'Blake Wesley', 0, true, -3.0, -0.6),
  ('Portland Trail Blazers', 'Rayan Rupert', 0, false, -4.6, -0.5),
  ('Sacramento Kings', 'Domantas Sabonis', 0, true, 0.8, -0.5),
  ('Sacramento Kings', 'DeMar DeRozan', 17, true, 1.5, -1.6),
  ('Sacramento Kings', 'Keegan Murray', 0, true, -0.4, 0.6),
  ('Sacramento Kings', 'Keon Ellis', 0, false, -1.8, 0.3),
  ('Sacramento Kings', 'Dennis Schröder', 0, false, -0.6, -0.8),
  ('Sacramento Kings', 'Malik Monk', 30, true, 0.5, -1.0),
  ('Sacramento Kings', 'Zach LaVine', 0, true, 0.8, -1.5),
  ('Sacramento Kings', 'Devin Carter', 30, true, -1.5, -0.4),
  ('Sacramento Kings', 'Precious Achiuwa', 30, true, -2.2, 0.9),
  ('Sacramento Kings', 'De''Andre Hunter', 0, true, -0.2, -1.1),
  ('Sacramento Kings', 'Russell Westbrook', 0, true, -1.2, -0.6),
  ('Sacramento Kings', 'Daeqwon Plowden', 20, true, -1.3, -1.6),
  ('Sacramento Kings', 'Isaiah Stevens', 0, true, -1.6, -0.8),
  ('Sacramento Kings', 'Dylan Cardwell', 30, true, -2.6, -0.3),
  ('Sacramento Kings', 'Maxime Raynaud', 30, true, -1.7, -1.2),
  ('Sacramento Kings', 'Nique Clifford', 30, true, -3.6, -0.4),
  ('Sacramento Kings', 'Doug McDermott', 10, true, -1.0, -2.2),
  ('Sacramento Kings', 'Killian Hayes', 13, true, -2.6, 0.0),
  ('San Antonio Spurs', 'Victor Wembanyama', 0, true, 4.5, 3.9),
  ('San Antonio Spurs', 'Luke Kornet', 30, true, 0.4, 0.5),
  ('San Antonio Spurs', 'De''Aaron Fox', 30, true, 2.2, 1.0),
  ('San Antonio Spurs', 'Harrison Barnes', 25, true, 0.5, -0.7),
  ('San Antonio Spurs', 'Stephon Castle', 0, true, 1.7, 1.3),
  ('San Antonio Spurs', 'Jordan McLaughlin', 0, true, -2.2, -0.1),
  ('San Antonio Spurs', 'Kelly Olynyk', 25, true, -1.0, -0.4),
  ('San Antonio Spurs', 'Devin Vassell', 30, true, 1.4, 0.4),
  ('San Antonio Spurs', 'Julian Champagnie', 30, true, 1.6, 0.7),
  ('San Antonio Spurs', 'Lindy Waters III', 20, true, -1.0, -0.3),
  ('San Antonio Spurs', 'Keldon Johnson', 20, true, -0.1, 0.0),
  ('San Antonio Spurs', 'Dylan Harper', 30, true, 0.2, 1.4),
  ('San Antonio Spurs', 'Carter Bryant', 0, true, -2.7, -0.4),
  ('San Antonio Spurs', 'David Jones Garcia', 0, true, -1.7, -0.3),
  ('San Antonio Spurs', 'Bismack Biyombo', 0, true, -3.8, -1.0),
  ('San Antonio Spurs', 'Harrison Ingram', 0, true, -3.4, -0.6),
  ('Toronto Raptors', 'Immanuel Quickley', 16, true, 2.2, 0.1),
  ('Toronto Raptors', 'Jakob Poeltl', 25, true, -0.7, 0.7),
  ('Toronto Raptors', 'Scottie Barnes', 34, true, 0.4, 1.6),
  ('Toronto Raptors', 'Brandon Ingram', 34, true, 0.8, -0.2),
  ('Toronto Raptors', 'RJ Barrett', 30, true, 1.3, -0.6),
  ('Toronto Raptors', 'Sandro Mamukelashvili', 10, true, 0.5, -0.1),
  ('Toronto Raptors', 'Ja''Kobe Walter', 25, true, -2.2, 0.1),
  ('Toronto Raptors', 'Ochai Agbaji', 0, false, -2.1, 0.2),
  ('Toronto Raptors', 'Jamal Shead', 36, true, -0.3, 0.7),
  ('Toronto Raptors', 'Garrett Temple', 0, true, -3.5, 0.9),
  ('Toronto Raptors', 'Collin Murray-Boyles', 10, true, -1.3, 1.4),
  ('Toronto Raptors', 'Gradey Dick', 20, true, -1.1, -1.2),
  ('Toronto Raptors', 'Jonathan Mogbo', 0, true, -3.3, 0.1),
  ('Toronto Raptors', 'Chucky Hepburn', 0, true, -1.0, -0.7),
  ('Toronto Raptors', 'Alijah Martin', 0, true, -1.9, -0.2),
  ('Toronto Raptors', 'Jamison Battle', 0, true, -1.5, -0.6),
  ('Utah Jazz', 'Lauri Markkanen', 0, true, 3.6, 0.6),
  ('Utah Jazz', 'Jaren Jackson Jr', 0, true, 0.1, 1.5),
  ('Utah Jazz', 'Kevin Love', 0, true, 0.1, -0.8),
  ('Utah Jazz', 'Walker Kessler', 0, true, -0.4, 0.8),
  ('Utah Jazz', 'Jusuf Nurkic', 0, true, -1.2, 1.3),
  ('Utah Jazz', 'Vince Williams Jr', 0, true, -0.7, 0.4),
  ('Utah Jazz', 'Svi Mykhailiuk', 0, true, 0.0, -0.5),
  ('Utah Jazz', 'John Konchar', 20, true, -2.8, 1.0),
  ('Utah Jazz', 'Oscar Tshiebwe', 15, true, -0.9, -1.1),
  ('Utah Jazz', 'Elijah Harkless', 0, true, -1.8, 0.6),
  ('Utah Jazz', 'Georges Niang', 0, true, 0.5, -2.1),
  ('Utah Jazz', 'Kyle Filipowski', 30, true, -0.3, -1.6),
  ('Utah Jazz', 'Ace Bailey', 0, true, -1.0, -1.2),
  ('Utah Jazz', 'Brice Sensabaugh', 29, true, 1.4, -2.0),
  ('Utah Jazz', 'Taylor Hendricks', 0, false, -2.6, -1.6),
  ('Utah Jazz', 'Walter Clayton Jr', 0, false, 0.0, -2.0),
  ('Utah Jazz', 'Keyonte George', 0, true, 2.2, -2.9),
  ('Utah Jazz', 'Blake Hinson', 30, true, -1.2, -1.6),
  ('Utah Jazz', 'Mo Bamba', 0, true, -2.2, -0.8),
  ('Utah Jazz', 'Isaiah Collier', 0, true, -1.4, -2.5),
  ('Utah Jazz', 'Anderson Garcia', 30, true, -2.5, -0.1),
  ('Utah Jazz', 'Bez Mbeng', 30, true, -4.2, 0.2),
  ('Utah Jazz', 'Cody Williams', 36, true, -3.3, -1.8),
  ('Washington Wizards', 'Trae Young', 0, true, 3.4, -2.2),
  ('Washington Wizards', 'CJ McCollum', 0, false, 1.3, -1.6),
  ('Washington Wizards', 'Khris Middleton', 0, false, 0.2, -0.4),
  ('Washington Wizards', 'Justin Chmpagnie', 15, true, -0.3, -1.3),
  ('Washington Wizards', 'Marvin Bagley III', 0, false, -0.6, -0.7),
  ('Washington Wizards', 'Cam Whitmore', 0, true, -1.2, -1.3),
  ('Washington Wizards', 'Kyshawn George', 0, true, -0.6, -0.3),
  ('Washington Wizards', 'Alex Sarr', 0, true, -0.4, -0.8),
  ('Washington Wizards', 'Bub Carrington', 30, true, -1.5, -0.9),
  ('Washington Wizards', 'Tre Johnson', 15, true, -0.3, -1.0),
  ('Washington Wizards', 'Will Riley', 30, true, -3.0, -1.5),
  ('Washington Wizards', 'Jonathan Pierre', 30, true, -2.7, -0.3),
  ('Washington Wizards', 'Bilal Coulibaly', 15, true, -2.3, 0.3),
  ('Washington Wizards', 'Tristan Vukcevic', 15, true, -0.9, -1.8),
  ('Washington Wizards', 'Jamir Watkins', 30, true, -3.7, -0.1),
  ('Washington Wizards', 'Corey Kispert', 0, false, -0.9, -2.4),
  ('Washington Wizards', 'Malaki Branham', 0, true, -2.6, -1.4),
  ('Washington Wizards', 'Sharife Cooper', 30, true, -2.9, -1.6),
  ('Washington Wizards', 'AJ Johnson', 0, false, -3.8, -1.5),
  ('Washington Wizards', 'Anthony Gill', 30, true, -3.1, -1.3);

select team, sum(mpg) as minuutit, count(*) filter (where in_team) as pelaajia
from season_start_roster group by team order by team;
