-- Win totalit Pinnaclen linjoista ja kertoimista (1.10.2026): marginaalista puhdistettu P(yli) muunnettu
-- odotetuiksi voitoiksi (normaalijakauma, hajonta 8 voittoa) ja skaalattu niin, että summa on 1230. Clippers ennallaan (30.5).
alter table team_stats add column if not exists win_total numeric;
update team_stats set win_total = 44.1 where team = 'Atlanta Hawks';
update team_stats set win_total = 50.0 where team = 'Boston Celtics';
update team_stats set win_total = 23.5 where team = 'Brooklyn Nets';
update team_stats set win_total = 37.1 where team = 'Charlotte Hornets';
update team_stats set win_total = 28.6 where team = 'Chicago Bulls';
update team_stats set win_total = 47.4 where team = 'Cleveland Cavaliers';
update team_stats set win_total = 33.4 where team = 'Dallas Mavericks';
update team_stats set win_total = 48.1 where team = 'Denver Nuggets';
update team_stats set win_total = 47.9 where team = 'Detroit Pistons';
update team_stats set win_total = 38.6 where team = 'Golden State Warriors';
update team_stats set win_total = 47.8 where team = 'Houston Rockets';
update team_stats set win_total = 44.6 where team = 'Indiana Pacers';
update team_stats set win_total = 45.7 where team = 'Los Angeles Lakers';
update team_stats set win_total = 28.1 where team = 'Memphis Grizzlies';
update team_stats set win_total = 44.8 where team = 'Miami Heat';
update team_stats set win_total = 24.6 where team = 'Milwaukee Bucks';
update team_stats set win_total = 48.1 where team = 'Minnesota Timberwolves';
update team_stats set win_total = 28.7 where team = 'New Orleans Pelicans';
update team_stats set win_total = 51.7 where team = 'New York Knicks';
update team_stats set win_total = 61.2 where team = 'Oklahoma City Thunder';
update team_stats set win_total = 44.4 where team = 'Orlando Magic';
update team_stats set win_total = 50.5 where team = 'Philadelphia 76ers';
update team_stats set win_total = 39.1 where team = 'Phoenix Suns';
update team_stats set win_total = 41.1 where team = 'Portland Trail Blazers';
update team_stats set win_total = 21.4 where team = 'Sacramento Kings';
update team_stats set win_total = 60.0 where team = 'San Antonio Spurs';
update team_stats set win_total = 46.4 where team = 'Toronto Raptors';
update team_stats set win_total = 38.6 where team = 'Utah Jazz';
update team_stats set win_total = 34.3 where team = 'Washington Wizards';
update team_stats set win_total = 30.5 where team = 'Los Angeles Clippers';

-- Vedonlyöntilinjat ja kertoimet (Kausi-sivun EV lasketaan näitä vastaan).
alter table team_stats add column if not exists wt_line numeric;
alter table team_stats add column if not exists wt_over numeric;
alter table team_stats add column if not exists wt_under numeric;
notify pgrst, 'reload schema';
update team_stats set wt_line = 43.5, wt_over = 1.735, wt_under = 2.12 where team = 'Atlanta Hawks';
update team_stats set wt_line = 50.5, wt_over = 1.934, wt_under = 1.884 where team = 'Boston Celtics';
update team_stats set wt_line = 24.5, wt_over = 2.04, wt_under = 1.793 where team = 'Brooklyn Nets';
update team_stats set wt_line = 38.5, wt_over = 2.13, wt_under = 1.729 where team = 'Charlotte Hornets';
update team_stats set wt_line = 28.5, wt_over = 1.826, wt_under = 2.0 where team = 'Chicago Bulls';
update team_stats set wt_line = 47.5, wt_over = 1.847, wt_under = 1.98 where team = 'Cleveland Cavaliers';
update team_stats set wt_line = 34.5, wt_over = 2.06, wt_under = 1.775 where team = 'Dallas Mavericks';
update team_stats set wt_line = 49.5, wt_over = 2.12, wt_under = 1.74 where team = 'Denver Nuggets';
update team_stats set wt_line = 50.5, wt_over = 2.44, wt_under = 1.571 where team = 'Detroit Pistons';
update team_stats set wt_line = 41.5, wt_over = 2.54, wt_under = 1.531 where team = 'Golden State Warriors';
update team_stats set wt_line = 47.5, wt_over = 1.781, wt_under = 2.06 where team = 'Houston Rockets';
update team_stats set wt_line = 44.5, wt_over = 1.826, wt_under = 2.0 where team = 'Indiana Pacers';
update team_stats set wt_line = 45.5, wt_over = 1.806, wt_under = 2.03 where team = 'Los Angeles Lakers';
update team_stats set wt_line = 28.5, wt_over = 1.909, wt_under = 1.909 where team = 'Memphis Grizzlies';
update team_stats set wt_line = 46.5, wt_over = 2.2, wt_under = 1.689 where team = 'Miami Heat';
update team_stats set wt_line = 25.5, wt_over = 2.01, wt_under = 1.819 where team = 'Milwaukee Bucks';
update team_stats set wt_line = 48.5, wt_over = 1.909, wt_under = 1.909 where team = 'Minnesota Timberwolves';
update team_stats set wt_line = 28.5, wt_over = 1.806, wt_under = 2.02 where team = 'New Orleans Pelicans';
update team_stats set wt_line = 52.5, wt_over = 2.0, wt_under = 1.833 where team = 'New York Knicks';
update team_stats set wt_line = 60.5, wt_over = 1.719, wt_under = 2.14 where team = 'Oklahoma City Thunder';
update team_stats set wt_line = 43.5, wt_over = 1.689, wt_under = 2.2 where team = 'Orlando Magic';
update team_stats set wt_line = 50.5, wt_over = 1.833, wt_under = 1.99 where team = 'Philadelphia 76ers';
update team_stats set wt_line = 39.5, wt_over = 1.917, wt_under = 1.9 where team = 'Phoenix Suns';
update team_stats set wt_line = 41.5, wt_over = 1.909, wt_under = 1.909 where team = 'Portland Trail Blazers';
update team_stats set wt_line = 21.5, wt_over = 1.847, wt_under = 1.97 where team = 'Sacramento Kings';
update team_stats set wt_line = 60.5, wt_over = 1.934, wt_under = 1.877 where team = 'San Antonio Spurs';
update team_stats set wt_line = 45.5, wt_over = 1.689, wt_under = 2.2 where team = 'Toronto Raptors';
update team_stats set wt_line = 35.5, wt_over = 1.432, wt_under = 2.88 where team = 'Utah Jazz';
update team_stats set wt_line = 35.5, wt_over = 2.07, wt_under = 1.775 where team = 'Washington Wizards';
update team_stats set wt_line = 30.5, wt_over = null, wt_under = null where team = 'Los Angeles Clippers';
select team, win_total, wt_line, wt_over, wt_under from team_stats order by win_total desc;
